### ISSUE TITLE
Has anyone successfully used this to run code through a pytorch model?

### ISSUE THREAD

**Issue by liuyiming199721** [joemathai/clever_robustness_pytorch#1]
Has anyone successfully used this to run code through a pytorch model?

**Comment by joemathai** [comment]
A pull request was merged into ART in the past. You can find their implementation here https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/metrics/metrics.py

**Comment by liuyiming199721** [comment]
Thanks, and replace your code with the def clever section of metrics.py? Can you find a complete pytorch resnet project file? Or any other network model. Thank you very much.

**Comment by liuyiming199721** [comment]
> 过去，拉取请求已合并到 ART 中。您可以在这里找到它们的实现https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/metrics/metrics.py

Thanks, and replace your code with the def clever section of metrics.py? Can you find a complete pytorch resnet project file? Or any other network model. Thank you very much.

**Comment by liuyiming199721** [comment]
> 过去，拉取请求已合并到 ART 中。您可以在这里找到它们的实现https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/metrics/metrics.py
Thank you very much. May I have your contact information to communicate with you? My vx (wechat) is liu15176678823

**Comment by joemathai** [comment]
You can find a small example here in the unit-tests of ART https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/75b38a1dc79c3606402c8f12c98ac4220b591198/tests/metrics/test_metrics.py#L333
